name: 观察者
url: http://qwivan.github.io
description: Big brother is watching you.

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
